// ---------------------------------------------------------------------------
// Game state: persistence, party, roster, per-student stats, leaderboard,
// run lifecycle. Everything is stored in this browser (classroom computer).
// Data is shaped so it can later be pushed to a shared backend unchanged.
// ---------------------------------------------------------------------------


function defaultState() {
  return {
    unlockedRealms: CONFIG.DEFAULT_UNLOCKED.slice(),
    teacherAutoUnlock: false,
    soundOn: true,
    ember: 0,              // meta-currency, survives a party wipe
    permanentPerks: [],    // legacy; migrated into realmPerks below
    realmPerks: {},        // realmId -> [perkId] — perks are per REALM now
    roster: null,          // { className, students:[name,...] }
    studentStats: {},      // name -> { correct, wrong, monsters, damage, relics, teamups }
    leaderboard: [],       // completed run records
    perksEnabled: true,    // teacher can switch the Forge off for a class
    coachOn: true,         // in-game explanations, first time only
    coachSeen: {},
    shortRealm: false,     // a 9-layer map for a single period
    run: null,
  };
}

let STATE = loadState();

function loadState() {
  try {
    const raw = localStorage.getItem(CONFIG.SAVE_KEY);
    if (!raw) return defaultState();
    const st = Object.assign(defaultState(), JSON.parse(raw));
    migratePerks(st);
    migrateRun(st);
    return st;
  } catch (e) {
    console.warn("save load failed, starting fresh", e);
    return defaultState();
  }
}

// A run saved by an older version won't have the newer fields. Fill them in
// rather than wiping a class's progress in the middle of a lesson.
// v5.5: perks used to be one flat list that applied to every realm forever.
// Anything a class already bought is honoured, but only in Realm 1 - from
// Realm 2 on, each unit starts its own climb.
function migratePerks(st) {
  st.realmPerks = st.realmPerks || {};
  if (Array.isArray(st.permanentPerks) && st.permanentPerks.length &&
      !st.realmPerks[1]) {
    st.realmPerks[1] = st.permanentPerks.slice();
  }
}

function migrateRun(st) {
  const r = st.run;
  if (!r) return;
  if (!Array.isArray(r.potions)) r.potions = [];
  if (!r.shopStock)              r.shopStock = {};
  // v5.7 added a gear row; stock generated by an older version has none
  Object.values(r.shopStock).forEach(stock => {
    if (stock && !Array.isArray(stock.gear)) stock.gear = [];
  });
  if (!Array.isArray(r.relics))  r.relics = [];
  if (!Array.isArray(r.absent))  r.absent = [];
  if (typeof r.shieldActive  !== "boolean") r.shieldActive  = false;
  if (typeof r.clarityActive !== "boolean") r.clarityActive = false;
  if (typeof r.usedLastStand  !== "boolean") r.usedLastStand  = false;
  if (typeof r.usedLastBreath !== "boolean") r.usedLastBreath = false;
  if (typeof r.usedEcho       !== "boolean") r.usedEcho       = false;
  // v5.8 events
  if (!Array.isArray(r.missedQs))   r.missedQs   = [];
  if (!Array.isArray(r.eventsSeen)) r.eventsSeen = [];
  if (typeof r.idolTaken     !== "boolean") r.idolTaken     = false;
  if (typeof r.longRoadTaken !== "boolean") r.longRoadTaken = false;
  // v5.7: Last Stands became a counter so the relic and the perk can stack.
  if (typeof r.lastStandsUsed !== "number") {
    r.lastStandsUsed = (r.usedLastStand ? 1 : 0) + (r.usedLastBreath ? 1 : 0);
  }
  // v5.3: Momentum is gone. Old saves carry momentum/moRouse/moGuard - they
  // are simply ignored rather than migrated, since nothing reads them now.
  if (typeof r.stake          !== "string")  r.stake          = "safe";
  if (typeof r.focusUsed      !== "boolean") r.focusUsed      = false;
  if (typeof r.focusArmed     !== "boolean") r.focusArmed     = false;
  if (typeof r.teamUpsUsed    !== "number")  r.teamUpsUsed    = 0;
  if (!r.stats) r.stats = { correct: 0, wrong: 0, monsters: 0, teamups: 0 };
  // Older maps contain no shop rooms - harmless, they just won't appear
  // until the next run.
}

function saveState() {
  try {
    localStorage.setItem(CONFIG.SAVE_KEY, JSON.stringify(STATE));
  } catch (e) {
    console.warn("save failed", e);
  }
}

function factoryReset() {
  STATE = defaultState();
  saveState();
}

// Start of a new term with the same class: keep who is in the room, throw
// away everything they earned. Between this and Factory Reset there is now a
// reset for every situation a teacher actually has.
function newTermReset() {
  const roster = STATE.roster;
  STATE = defaultState();
  STATE.roster = roster;
  if (roster) roster.students.forEach(ensureStudentStats);
  saveState();
}

// A leaver or a transfer. Previously the only way to remove one name was to
// wipe the whole save.
function removeStudent(name) {
  if (!STATE.roster) return;
  STATE.roster.students = STATE.roster.students.filter(n => n !== name);
  delete STATE.studentStats[name];
  const run = STATE.run;
  if (run) {
    run.turnQueue = (run.turnQueue || []).filter(n => n !== name);
    run.absent = (run.absent || []).filter(n => n !== name);
    if (run.currentStudent === name) nextStudent();
  }
  saveState();
}

// ---------------------------------------------------------------------------
// roster + student stats
// ---------------------------------------------------------------------------
function setRoster(className, students, partyName) {
  STATE.roster = {
    className: className.trim(),
    partyName: (partyName || "").trim(),
    students: students.slice(),
  };
  students.forEach(ensureStudentStats);
  saveState();
}

function ensureStudentStats(name) {
  if (!STATE.studentStats[name]) {
    STATE.studentStats[name] = {
      correct: 0, wrong: 0, monsters: 0, damage: 0, relics: 0, teamups: 0,
    };
  }
  return STATE.studentStats[name];
}

function bumpStat(name, key, by = 1) {
  if (!name) return;
  const s = ensureStudentStats(name);
  s[key] = (s[key] || 0) + by;
  saveState();
}

// Pick the next student. Avoids repeating anyone until everyone has had a
// turn (a shuffled queue), so nobody gets picked twice while others wait.
function nextStudent(exclude = null) {
  const run = STATE.run;
  if (!run || !STATE.roster || !STATE.roster.students.length) return null;
  if (!run.turnQueue || run.turnQueue.length === 0) {
    run.turnQueue = shuffle(STATE.roster.students);
  }
  let idx = 0;
  if (exclude && run.turnQueue.length > 1) {
    while (run.turnQueue[idx] === exclude && idx < run.turnQueue.length - 1) idx++;
  }
  const name = run.turnQueue.splice(idx, 1)[0];
  run.currentStudent = name;
  saveState();
  return name;
}

// Reroll = pass this turn to somebody else.
//
// It used to mean "this student is ABSENT" and wrote them out of the run
// permanently. It is an unguarded, unlimited button sitting next to the answer
// choices, so it was a perfect "I don't want to answer" escape hatch: ten
// presses marked the entire class absent, their names greyed out for the rest
// of the realm, with no way to undo it from the game screen. Marking a child
// absent is a register decision and belongs in the Teacher Menu; this button
// now just moves the turn on.
function rerollStudent() {
  const run = STATE.run;
  if (!run) return null;
  const absent = run.currentStudent;
  if (absent) {
    run.turnQueue = (run.turnQueue || []).filter(n => n !== absent);
  }
  // rebuild the queue from present students only
  if (!run.turnQueue || run.turnQueue.length === 0) {
    const present = STATE.roster.students.filter(
      n => !(run.absent || []).includes(n));
    run.turnQueue = shuffle(present.length ? present : STATE.roster.students);
  }
  return nextStudent(absent);
}

// ---------------------------------------------------------------------------
// run lifecycle
// ---------------------------------------------------------------------------
function startNewRun(realmId, heroId) {
  const realm = REALMS[realmId];
  const map = generateMap(realm);
  // the per-realm ramp: one fewer starting heart every fourth realm
  const rampHearts = Math.floor((realmId - 1) /
    ((CONFIG.REALM_RAMP && CONFIG.REALM_RAMP.heartsPer) || 99));
  let hearts = Math.max(5, CONFIG.START_HEARTS - rampHearts);
  if (typeof hasPerk === "function" && hasPerk("second_wind")) hearts += 1;

  STATE.run = {
    realmId,
    heroId,
    map,
    currentNodeId: map.nodes[0].id,
    visitedNodeIds: [map.nodes[0].id],
    hearts,
    maxHearts: Math.max(CONFIG.START_HEARTS, hearts),
    shards: 0,
    relics: [],
    potions: [],          // consumable ids held by the party
    weapon: null,         // equipped gear id
    armour: null,
    enchants: {},         // slot -> enchantment id
    shields: 0,           // absorbed before hearts
    streak: 0,            // consecutive correct answers
    bestStreak: 0,
    stake: "safe",        // this question's stake: "safe" or "risky"
    focusUsed: false,     // Focus is once per FIGHT, reset by resetFocus()
    focusArmed: false,
    teamUpsUsed: 0,       // Team Up is limited per RUN now, not per monster
    campfiresUsed: 0,
    shardMultiplier: 1,
    shieldActive: false,  // Storm Shield blocks the next hit
    clarityActive: false, // Potion of Clarity trims the next question
    shopStock: {},        // nodeId -> generated stock, so a shop is stable
    coveredKeys: [],       // curriculum items already tested this run
    missedQs: [],          // cover keys the class got WRONG (Echoing Hall)
    eventsSeen: [],        // event ids already offered this run
    idolTaken: false,      // Whispering Idol: +50% shards, +1 wrong-answer damage
    longRoadTaken: false,
    usedQuestionIdx: [],   // avoid repeating the exact same question
    usedLuckyCharm: false,
    usedEcho: false,
    usedLastStand: false,
    lastStandsUsed: 0,    // counter: 1 base + 1 per Last Breath relic / perk
    usedLastBreath: false, // the Last Breath relic grants a second one
    startedAt: Date.now(),
    turnQueue: null,
    currentStudent: null,
    absent: [],
    encounter: null,       // active monster fight
    boss: null,
    stats: { correct: 0, wrong: 0, monsters: 0, teamups: 0 },
  };
  saveState();
  return STATE.run;
}

function currentRealm() {
  return STATE.run ? REALMS[STATE.run.realmId] : null;
}

// Remember what the class got wrong this run. The Echoing Hall event brings
// one back for a second attempt, which is spaced repetition dressed up as a
// reward - and it targets exactly the material they have demonstrably not got.
function noteMissed(q) {
  const run = STATE.run;
  if (!run || !q || !q.cover) return;
  run.missedQs = run.missedQs || [];
  // most recent last, and never more than a handful
  run.missedQs = run.missedQs.filter(k => k !== q.cover);
  run.missedQs.push(q.cover);
  if (run.missedQs.length > 12) run.missedQs.shift();
  saveState();
}

function markCovered(cover) {
  const run = STATE.run;
  if (run && cover && !run.coveredKeys.includes(cover)) {
    run.coveredKeys.push(cover);
  }
}

// Pick a question, preferring curriculum items not yet covered this run and
// avoiding exact repeats.
//
// `elite` mixes in the tier-4 bank: harder questions that ask students to USE
// the language rather than recognise it. Only Elite rooms and the Boss ever
// pass it, so an ordinary Fight stays within reach of the whole class.
function drawQuestion(realm, elite = false) {
  const run = STATE.run;
  // A run can end between a turn being scheduled and the question being drawn
  // - a party wipe mid-animation nulls STATE.run, and currentRealm() then
  // returns null. Callers pass that null straight in.
  if (!run || !realm) return null;
  const eliteBank = realm.eliteQuestions || [];
  const all = (elite && eliteBank.length && Math.random() < 0.65)
    ? eliteBank
    : realm.questions;
  const tag = i => (all === realm.questions ? i : "e" + i);
  let pool = all
    .map((q, i) => ({ q, i }))
    .filter(x => !run.usedQuestionIdx.includes(tag(x.i)));
  if (pool.length === 0) {
    run.usedQuestionIdx = run.usedQuestionIdx.filter(
      x => (all === realm.questions) !== (typeof x === "number"));
    pool = all.map((q, i) => ({ q, i }));
  }
  const fresh = pool.filter(x => !run.coveredKeys.includes(x.q.cover));
  const chosen = pick(fresh.length ? fresh : pool);
  // the used-index list is per-bank, so tag elite draws to keep them apart
  run.usedQuestionIdx.push(all === realm.questions ? chosen.i : "e" + chosen.i);
  saveState();
  return chosen.q;
}

// ---------------------------------------------------------------------------
// party resources
// ---------------------------------------------------------------------------
function damage(n = 1) {
  const run = STATE.run;
  if (!run) return { blocked: false, dead: false };

  if (run.shieldActive) {                       // Storm Shield potion
    run.shieldActive = false;
    saveState();
    return { blocked: true, blockedBy: "Storm Shield", dead: false };
  }
  if (!run.usedLuckyCharm && hasRelic("lucky_charm")) {
    run.usedLuckyCharm = true;
    saveState();
    return { blocked: true, blockedBy: "Lucky Charm", dead: false };
  }

  // Shields soak damage before hearts are touched.
  let absorbed = 0;
  if (run.shields > 0) {
    absorbed = Math.min(run.shields, n);
    run.shields -= absorbed;
    n -= absorbed;
  }
  run.hearts = Math.max(0, run.hearts - n);
  saveState();
  return {
    blocked: n === 0 && absorbed > 0,
    blockedBy: absorbed > 0 ? "Shields" : null,
    absorbed, dealt: n,
    dead: run.hearts <= 0,
  };
}

// ---------------------------- shields / gear -------------------------------
function addShields(n) {
  STATE.run.shields = Math.min(99, (STATE.run.shields || 0) + n);
  saveState();
}

// Shields are topped up at a REST POINT only - a Rest room or a Safe Path -
// never on walking into an ordinary room. Free full armour every room was why
// armour felt weightless; now it is a resource the class has to manage.
function refillShields() {
  const run = STATE.run;
  if (!run) return 0;
  let gain = CONFIG.REST_SHIELDS || 0;
  const armour = run.armour ? gearById(run.armour) : null;
  if (armour) {
    if (armour.id === "windwarden")   gain += 3;
    if (armour.id === "aegis_mantle") gain += 5;
  }
  if (run.enchants && run.enchants.armour === "ward_etch") gain += 2;
  if (hasRelic("aegis_charm")) gain += 2;
  if (hasRelic("storm_crown")) gain += 3;
  if (hasPerk("warded")) gain += 2;
  // top up to the full figure rather than stacking on what's left, so a
  // rest is always worth the same and never snowballs
  const before = run.shields || 0;
  run.shields = Math.max(before, gain);
  saveState();
  return Math.max(0, run.shields - before);
}

// Potions and shop patch kits add shields on top of whatever is left.
function addShieldTop(n) {
  const run = STATE.run;
  if (!run) return 0;
  run.shields = Math.min(99, (run.shields || 0) + n);
  saveState();
  return n;
}

function equipGear(gear) {
  const run = STATE.run;
  const slot = gear.slot;
  const previous = run[slot];
  run[slot] = gear.id;
  if (previous !== gear.id) run.enchants[slot] = null;   // etching is lost
  saveState();
  return previous ? gearById(previous) : null;
}

function availableGear(slot = null) {
  const run = STATE.run;
  let pool = ALL_GEAR.filter(g => g.id !== run.weapon && g.id !== run.armour);
  if (slot) pool = pool.filter(g => g.slot === slot);
  return pool.length ? pick(pool) : null;
}

function applyEnchant(slot, enchantId) {
  STATE.run.enchants[slot] = enchantId;
  saveState();
}

// ---------------------------- streaks --------------------------------------
function bumpStreak() {
  const run = STATE.run;
  run.streak = (run.streak || 0) + 1;
  run.bestStreak = Math.max(run.bestStreak || 0, run.streak);
  saveState();
  return run.streak;
}
function resetStreak() {
  if (STATE.run) { STATE.run.streak = 0; saveState(); }
}

function heal(n = 1) {
  const run = STATE.run;
  if (!run) return;
  run.hearts = Math.min(run.maxHearts, run.hearts + n);
  saveState();
}

function addShards(n) {
  const run = STATE.run;
  let mult = run.shardMultiplier || 1;
  if (hasRelic("coin_purse")) mult += 0.25;
  const gained = Math.max(1, Math.round(n * mult));
  run.shards += gained;
  saveState();
  return gained;
}
function addEmber(n)  { STATE.ember += n; saveState(); }

function hasRelic(id) {
  return !!(STATE.run && STATE.run.relics.some(r => r.id === id));
}

function addRelic(relic) {
  STATE.run.relics.push(relic);
  if (relic.id === "storm_crown") {
    STATE.run.maxHearts += 1;
    STATE.run.hearts = Math.min(STATE.run.maxHearts, STATE.run.hearts + 1);
  }
  if (relic.id === "second_wind") {
    STATE.run.maxHearts += 1;
    STATE.run.hearts = Math.min(STATE.run.maxHearts, STATE.run.hearts + 1);
  }
  saveState();
}

// A relic the party doesn't already hold. `rarities` narrows the pool.
// Relic rarity used to be consumed by exactly one thing: the shop price.
// Drops themselves were uniform, so Giant-Slayer - an epic that halves every
// elite fight - was exactly as likely as a common, and one elite kill in nine
// handed a class a fight-halving relic. Rarity now weights the roll, which is
// what makes an epic a moment rather than a coin flip.
// Tuned against the actual pool (7 common, 7 uncommon, 3 rare, 3 epic) rather
// than picked as round numbers. A first pass at 50/30/15/5 put epics at 2.5%
// of drops - roughly one epic every twenty runs, which is not "you earned it",
// it is a lottery. At 50/30/25/15 an epic is 6.6% of drops, so about one run
// in nine contains one. Rare enough to be a moment, common enough to be a goal.
const RARITY_WEIGHT = { common: 50, uncommon: 30, rare: 25, epic: 15 };

function availableRelic(rarities = null) {
  const owned = STATE.run.relics.map(r => r.id);
  let pool = RELICS.filter(r => !owned.includes(r.id));
  if (rarities) {
    const narrowed = pool.filter(r => rarities.includes(r.rarity));
    if (narrowed.length) pool = narrowed;
  }
  if (!pool.length) return null;

  const total = pool.reduce((n, r) => n + (RARITY_WEIGHT[r.rarity] || 10), 0);
  let roll = Math.random() * total;
  for (const r of pool) {
    roll -= (RARITY_WEIGHT[r.rarity] || 10);
    if (roll <= 0) return r;
  }
  return pool[pool.length - 1];
}

// --------------------------- potions ---------------------------------------
// Capped. A run was picking up 8.5 potions - 6.5 of them from streak bonuses
// alone - so the party ended every realm holding six unopened bottles, the
// shop's potion row was worthless and the Deep Pack perk bought nothing.
// Returns false when the pack is full, so callers can say so instead of
// silently swallowing the reward.
function addPotion(id) {
  const run = STATE.run;
  if (!run) return false;
  const cap = CONFIG.MAX_POTIONS || 99;
  if (run.potions.length >= cap) return false;
  run.potions.push(id);
  saveState();
  return true;
}

function consumePotion(id) {
  const i = STATE.run.potions.indexOf(id);
  if (i === -1) return false;
  STATE.run.potions.splice(i, 1);
  saveState();
  return true;
}

// --------------------------- shop ------------------------------------------
// Stock is generated once per shop node and remembered, so re-entering or
// resuming the lesson shows the same wares.
function shopStockFor(nodeId) {
  const run = STATE.run;
  if (run.shopStock[nodeId]) return run.shopStock[nodeId];
  const owned = run.relics.map(r => r.id);
  const pool = shuffle(RELICS.filter(r => !owned.includes(r.id)));
  const relicPicks = [];
  // one better-than-common relic where possible, plus one of anything
  const fancy = pool.find(r => r.rarity !== "common");
  if (fancy) relicPicks.push(fancy);
  pool.forEach(r => {
    if (relicPicks.length < 2 && !relicPicks.includes(r)) relicPicks.push(r);
  });
  // GEAR. Until v5.7 the shop stocked relics and potions only, and the ONLY
  // other source was a 50% roll on an elite kill - 0.58 offers per whole run.
  // Six pieces of gear existed that a class could go an entire realm without
  // ever being shown. A gear row also gives late shards somewhere to go, which
  // is the other half of the surplus problem.
  const gearPool = shuffle(ALL_GEAR.filter(g =>
    g.id !== run.weapon && g.id !== run.armour));
  const gearPick = gearPool[0];

  const stock = {
    relics: relicPicks.map(r => ({ id: r.id, price: relicPrice(r), sold: false })),
    gear: gearPick
      ? [{ id: gearPick.id, price: GEAR_PRICE[gearPick.rarity] || 45, sold: false }]
      : [],
    potions: shuffle(POTIONS).slice(0, 3)
      .map(p => ({ id: p.id, price: p.price, sold: false })),
  };
  run.shopStock[nodeId] = stock;
  saveState();
  return stock;
}

function buyFromShop(nodeId, kind, index) {
  const run = STATE.run;
  const stock = run.shopStock[nodeId];
  if (!stock) return { ok: false, reason: "no stock" };
  const entry = stock[kind][index];
  if (!entry || entry.sold) return { ok: false, reason: "sold" };
  if (run.shards < entry.price) return { ok: false, reason: "poor" };
  run.shards -= entry.price;
  entry.sold = true;
  if (kind === "relics") addRelic(relicById(entry.id));
  else if (kind === "gear") equipGear(gearById(entry.id));
  else addPotion(entry.id);
  saveState();
  return { ok: true, item: itemById(entry.id), kind };
}

// ---------------------------------------------------------------------------
// end of run
// ---------------------------------------------------------------------------
function runScore() {
  const run = STATE.run;
  const minutes = Math.max(1, Math.round((Date.now() - run.startedAt) / 60000));
  const accuracy = run.stats.correct + run.stats.wrong > 0
    ? run.stats.correct / (run.stats.correct + run.stats.wrong) : 0;
  // shards + surviving hearts + accuracy, with only a light time factor so
  // classes aren't punished for discussing answers properly
  return Math.round(
    run.shards * 10 +
    run.hearts * 25 +
    accuracy * 200 +
    Math.max(0, 60 - minutes) * 2
  );
}

function clearRealm() {
  const run = STATE.run;
  const realmId = run.realmId;
  const score = runScore();
  const minutes = Math.max(1, Math.round((Date.now() - run.startedAt) / 60000));
  let emberGained = Math.round(run.shards / 2) + 5;
  if (run.relics.some(r => r.id === "ember_pouch")) {
    emberGained = Math.round(emberGained * 1.5);
  }
  addEmber(emberGained);

  STATE.leaderboard.push({
    className: STATE.roster ? STATE.roster.className : "Unnamed class",
    partyName: STATE.roster ? (STATE.roster.partyName || "") : "",
    heroId: run.heroId,
    bestStreak: run.bestStreak || 0,
    realmId,
    score,
    minutes,
    hearts: run.hearts,
    maxHearts: run.maxHearts,
    shards: run.shards,
    correct: run.stats.correct,
    wrong: run.stats.wrong,
    monsters: run.stats.monsters,
    date: new Date().toISOString().slice(0, 10),
  });
  STATE.leaderboard.sort((a, b) => b.score - a.score);
  STATE.leaderboard = STATE.leaderboard.slice(0, 50);

  if (STATE.teacherAutoUnlock && REALMS[realmId + 1] &&
      !STATE.unlockedRealms.includes(realmId + 1)) {
    STATE.unlockedRealms.push(realmId + 1);
  }
  const nextUnlocked = STATE.unlockedRealms.includes(realmId + 1);
  STATE.run = null;
  saveState();
  return { emberGained, score, minutes, nextUnlocked };
}

// Party wipe.
//
// This used to roll 50/50 between banking Ember and "keeping one relic". Two
// things were wrong with that:
//
//   1. The relic branch did NOTHING. It returned the relic's name, the results
//      screen printed it, and STATE.run was nulled two lines later. There was
//      no field anywhere that could hold it. So HALF of all wipes paid the
//      class absolutely nothing - and because the roll only happened when the
//      party was carrying relics, holding relics HALVED your expected reward
//      for dying.
//
//   2. Death paid `run.shards` undivided while victory paid `shards / 2`, so
//      losing was worth roughly twice as much Ember as winning. A class that
//      wanted Forge perks was better off farming the map and throwing the boss
//      fight. Ten-year-olds find that by accident and then on purpose.
//
// Dying now always pays, and always pays strictly less than winning.
function handleRunDeath() {
  const run = STATE.run;
  const gained = Math.round(run.shards / 3) + run.relics.length * 2 + 2;
  addEmber(gained);
  const outcome = { type: "ember", amount: gained };
  STATE.run = null;
  saveState();
  return outcome;
}

function teacherUnlock(realmId, unlocked) {
  if (unlocked && !STATE.unlockedRealms.includes(realmId)) {
    STATE.unlockedRealms.push(realmId);
  } else if (!unlocked) {
    STATE.unlockedRealms = STATE.unlockedRealms.filter(r => r !== realmId);
  }
  saveState();
}
